### ISSUE TITLE
incorrect highlighting of evil unified diff

### ISSUE THREAD

**Issue by retracile** [ymattw/cdiff#25]
A unified diff designed to confuse diff colorizers successfully confuses cdiff.

    --- evil.orig   2013-06-01 16:36:29.676003599 -0500
    +++ evil.new    2013-06-01 16:36:28.280056137 -0500
    @@ -1,12 +1,12 @@
     blah blah blah
    -humbug
    +bah humbug
     one two three
     four five six
    --- vim73/src/ui.c      2013-06-01 14:48:45.012467754 -0500
    +++ vim73/src/ui.c      2013-06-01 14:48:45.012467754 -0500
     @@ -1,6 +1,6 @@
     blah blah blah
     humbug
     one two three
     four five six
    -eight nine ten
    +seven eight nine ten
     zero

I found cdiff after writing [about the subtleties of diff colorizing](https://retracile.net/blog/2013/06/01/22.00) and it looked like you were doing a real parse of the diff.  But cdiff highlights the false filename lines as real filename lines and highlights the lines after those as cyan.

**Comment by ymattw** [comment]
I am bitten by this issue recently and want to fix it, see above commits.  Regression test did succeed.  However, I was lazy to instal dependencies and verify so my attempt failed the unit test.  I will fix that once got another cycle.

**Comment by ymattw** [comment]
Tests now fixed as well in commit 8f4d68e.
