### ISSUE TITLE
Problem when using side by side for diff of diff

### ISSUE THREAD

**Issue by mat813** [ymattw/cdiff#44]
Hi,

I'm a FreeBSD port committer, and in that capacity, I patch software a lot to coerce it to work on FreeBSD, or with newer version of software that upstream does not support yet, and in that capacity, we deal with a lot of patches, that change over time, and there's a bug in the side by side thingie.

To get the diff I'm talking about, you can run `svn diff -c 384636 https://svn0.eu.freebsd.org/ports
/head/devel/p5-Data-Alias/files/patch-Alias.xs`

The unified version of `cdiff` looks quite all right:

![capture d ecran 2015-04-24 a 15 08 21](https://cloud.githubusercontent.com/assets/75783/7319189/de571cb2-ea93-11e4-9ebc-539fcebddf19.png)

But the side by side eats all the + at the beginning of the lines, and does not look that good:

![capture d ecran 2015-04-24 a 15 08 38](https://cloud.githubusercontent.com/assets/75783/7319198/fe78b4f6-ea93-11e4-85ea-69b677baaae9.png)

**Comment by ymattw** [comment]
That's how it is designed. For unified diff we need the leading chars to
distinguish lines from original and new files, while for side by side diff
we do not need them, by nature left side is original and right side is new.

**Comment by mat813** [comment]
If you look at the screenshots, you'll see it eats *all* the + at the start of the line, not just the first one.

**Comment by ymattw** [comment]
The source is a patch file so the output looks confusing, but cdiff indeed only "eat" the first `-` or `+`.

**Comment by mat813** [comment]
I'm sorry, but no, it ate two.

line 147, it starts with `<space>+#ifdef...` shows up as `+#ifdef...`
line 148, starts with `++#if (PERL...` shows up as `#if (PERL...` it's eating both +, which is bad.

**Comment by mat813** [comment]
Note, it's eating in the side by side version, the unified diff version is fine.

**Comment by ymattw** [comment]
I got what you are saying, indeed it's a bug.  Probably wrong use of `lstrip`. I will fix it soon, thanks for reporting!

**Comment by ymattw** [comment]
Fixed in commit 10fa1e8, new version 0.9.7 available on pypi.
