### ISSUE TITLE
Tips for using cdiff as `git cdiff` :)

### ISSUE THREAD

**Issue by fgimian** [ymattw/cdiff#49]
Hey there, love this package :smile: 

I discovered that simply symlinking or renaming the executable to `git-cdiff` meant that I could now use:

```bash
git cdiff
```

Which felt a little more natural with all the other git commands.

Is there any other recommended way to do this?  Is it worth adding to the README file?

Cheers
Fotis

**Comment by mat813** [comment]
You can also just run `cdiff` and it'll do the same thing.

**Comment by fgimian** [comment]
True yeah, I think it's just a matter of habit really.  You get used to typing `git <bla>` for anything git related :smile:

**Comment by ymattw** [comment]
Thank you @fgimian, It is indeed a very useful tip, on the other hand,
cdiff is not just for git, I am not sure where is the right place to add
this tip, if you have a good idea, feel free to send me a pull request :)

**Comment by fgimian** [comment]
Sure @ymattw, I may pop it into the README.  I'll send a pull request at some point in the next day or two and we can close this off.

Keep up the great work!
Fotis

**Comment by ymattw** [comment]
Closed by #50.
