### ISSUE TITLE
problem with tabs on start of lines

### ISSUE THREAD

**Issue by mat813** [ymattw/cdiff#53]
```
$ printf "\tbar\n" > a
$ printf "\tbam\n" > b
$ diff -u a b
--- a   2016-03-24 13:37:11.867648342 +0100
+++ b   2016-03-24 13:37:07.492648951 +0100
@@ -1 +1 @@
-       bar
+       bam
```

with --color=never, the output is ok

```
$ diff -u a b|cdiff --color=never
--- a   2016-03-24 13:37:11.867648342 +0100
+++ b   2016-03-24 13:37:07.492648951 +0100
@@ -1 +1 @@
-       bar
+       bam
```

but with --color=auto, it does

![capture d ecran 2016-03-24 a 13 39 53](https://cloud.githubusercontent.com/assets/75783/14017188/fd0d6a64-f1c5-11e5-8040-6cd6e78c219b.png)

**Comment by ymattw** [comment]
Interesting, this works for me.

![image](https://cloud.githubusercontent.com/assets/1407119/14037109/3660f690-f27b-11e5-9f4d-a536e3f182c9.png)

What's your python version (`python -V`)?  Any special environment variable defined?  What's in your `$LESS`?  I see less behaves different from your screenshot.

**Comment by mat813** [comment]
```
$ python -V
Python 2.7.11
$ echo $LESS
-r -e -i -P?f%f :<STDIN> .?m (%i/%m) .?lt-- lignes %lt-%lb?L/%L. .?e-- [FIN] ?x-- Suivant\: %x .:-- ?pB%pB\%..%t
```

**Comment by mat813** [comment]
Mmm, got it, should use -R and not -r
