### ISSUE TITLE
Add linter output to diffs

### ISSUE THREAD

**Issue by rgeoghegan** [ymattw/cdiff#58]
Hi, I was wondering how open you would be to adding linter output to diffs? I currently have a branch of cdiff that does the following:

    $ cdiff --lint pep8 master
    diff --git a/cdiff.py b/cdiff.py
    index 229f848..d5b23da 100755
    --- a/cdiff.py
    +++ b/cdiff.py
    @@ -14,6 +14,8 @@ import signal
     import subprocess
     import select
     import difflib
    +import six
    +from collections import OrderedDict
     
     META_INFO = {
         'version'     : '0.9.8',                                            21: E203 whitespace before ':'
    [...]

I was about to package it up as a PR, but before fighting with python 2.5 and the like, I wanted to check if you were willing to accept linting as a feature, or should I just fork (and probably drop <2.7 support for my needs, fwiw)?

**Comment by ymattw** [comment]
Hi @rgeoghegan, thanks for your question.  I personally prefer to keep cdiff minimal and functional.  The lint output does not look like a normal *diff* so adding that behavior is a bit like breaking the KISS principle.  Is it possible to invent your feature on top of cdiff?

**Comment by rgeoghegan** [comment]
No probs. I will fork and go my own way.
