### ISSUE TITLE
Cannot use cdiff to compare two files

### ISSUE THREAD

**Issue by kirhgoff** [ymattw/cdiff#61]
I want to try cdiff just to compare two files in the folder. I type something like cdiff one.txt two.txt, and I get:

→ cdiff one.txt two.txt
fatal: two.txt: no such path in the working tree.
Use 'git <command> -- <path>...' to specify paths that do not exist locally.

Yes, and I call cdiff in the folder which is git repository, and files are not added to repo.

**Comment by ymattw** [comment]
Hi @kirhgoff, sorry to confuse you.  Cdiff reads the output from `git diff one.txt two.txt`, so you get the error from git because _two.txt_ is not version controlled.  It's by design, not a bug.  You may use `diff -u one.txt two.txt | cdiff` to meet your needs in this case.

**Comment by kirhgoff** [comment]
I suggest you put something like that to the help output as it is not clear that the only valid usage is git one. Anyway thanks for a great tool, I am using it every day!
