### ISSUE TITLE
Not able to use cdiff with git difftool

### ISSUE THREAD

**Issue by sbenedetto** [ymattw/cdiff#62]
First of all nice tool really.

I'm trying to use cdiff with git difftool but I always get the same error

fatal: external diff died, stopping at ....

Is it a known issue?

**Comment by ymattw** [comment]
Hi, cdiff does not act like a external diff tool, instead, it reads diff stream from other diff tool, for example, if cwd is inside a git work space, it will read the `git diff` output.

Please read the [Usage](https://github.com/ymattw/cdiff#usage) section in the README, you should be able to find useful examples.

I am going to close this but please let me know if you still have trouble using it. Thanks!
