### ISSUE TITLE
Unexpected behavior when parsing output of `git show` run on `stash` reflog-style refs

### ISSUE THREAD

**Issue by mosbasik** [ymattw/cdiff#65]
Probably not a bug; just me not being a cdiff wizard yet.  Haven't been able to figure out how to get it working yet, so help is appreciated! 

## Summary

Running something like this: `git show stash@{1} | cdiff -s` results in one column of mostly-cyan text that seems to be missing sections.  I expected it to behave similarly to `git show 4e2fc7b | cdiff -s`, which results in the whole diff rendered in two columns of diff-colored text.

I've tried several different stash indexes as well as just `git show stash` and all of them behaved the same way.

## To Reproduce

- Operating system: Ubuntu 14.04 (I know, I know)
- Version of `cdiff`: 1.0
- Installation method: iirc, `pip install cdiff` at the system level (binary is in `/usr/local/bin/cdiff`)

I dumped the results of the two git-show commands above to two files described below.  Create those files, then run the following:
```bash
cat git-show-stash.txt | cdiff -s  # unexpected behavior
cat git-show-sha.txt | cdiff -s  # expected behavior
```

## Files

**git-show-stash.txt**
```diff
commit 7c931ec949fd936ebdc43cb7cff58a6dabe88bec                                                                                                                                                                                      [0/5]
Merge: adc3783 a2a6bd5
Author: Firstname Lastname <username@domain.org>
Date:   Wed Jul 5 15:46:59 2017 -0500

    WIP on zone_delta_processing: adc3783 fix "no module named PythonMagick" error by switching to pgmagick

diff --cc rtls/urls.py
index 3ea1a0b,3ea1a0b..1cc7364
--- a/rtls/urls.py
+++ b/rtls/urls.py
@@@ -49,6 -49,6 +49,11 @@@ urlpatterns =
          views.api_disassociate_holder,
          name='api_disassociate_holder',
      ),
++    url(  # receives zone delta bundles, determines what actions to take (if any)
++        r'^(?i)api/triage-deltas/zone?$',
++        views.api_triage_zone_deltas,
++        name='api_triage_zone_deltas',
++    ),


      # --------- Map URLS ---------
diff --cc rtls/views.py
index 694ae27,694ae27..45e874c
--- a/rtls/views.py
+++ b/rtls/views.py
@@@ -6,6 -6,6 +6,7 @@@ from django.core.exceptions import Mult
  from django.core.mail import EmailMessage, send_mail
  from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
  from django.shortcuts import render, render_to_response, get_object_or_404
++from django.views.decorators.csrf import csrf_exempt

  from contacts.models import Person, Location
  from mosaiq.models import (
@@@ -75,6 -75,6 +76,16 @@@ def api_potential_holder_list(request)
      ))


++@csrf_exempt
++def api_triage_zone_deltas(request):
++    '''Receives a bundle of zone delta objects as a POST and determines what
++    actions need to be taken because of them, if any.'''
++    # print 'REMOTE_HOST', request.META['REMOTE_HOST']
++    # print 'HTTP_HOST', request.META['HTTP_HOST']
++    print '\nContents of POST:', request.POST, '\n'
++    return HttpResponse(status=200)
++
++
  def association_node_list(request):
      return render(request, 'rtls/association_node_list.html', {
          'registration_nodes': Node.objects.filter(topic='tag_reg')
```

**git-show-sha.txt**
```diff
commit 4e2fc7b5cb84a459f82e2f913a97a0b49f6e8b0d                                                                                                                                                                                      [0/5]
Author: Firstname Lastname <username@domain.org>
Date:   Fri Jun 30 11:47:52 2017 -0500

    document associate/disassociate urls

diff --git a/rtls/urls.py b/rtls/urls.py
index 378b0a7..3ea1a0b 100644
--- a/rtls/urls.py
+++ b/rtls/urls.py
@@ -39,12 +39,12 @@ urlpatterns = [
         views.api_potential_holder_list,
         name='api_potential_holder_list',
     ),
-    url(
+    url(  # used to associate a tag and a holder
         r'^(?i)api/association/associate/?$',
         views.api_associate,
         name='api_associate',
     ),
-    url(
+    url(  # used to disassociate a holder from any tag it may be associated with
         r'^(?i)api/association/disassociate/?$',
         views.api_disassociate_holder,
         name='api_disassociate_holder',
```

**Comment by ymattw** [comment]
The command `git show stash@{1}` outputs in diffstat format not unified
diff (patch) format.

If I remembered correctly, `git stash show -p stash@{1} | cdiff -s` should
work. You may want to make an alias for it if you use it frequently.

**Comment by mosbasik** [comment]
Thank you, that does the job.  Sorry it's taken a while to get back to you.

Spent a while reading through the `git-diff`, `git-stash` and `git-show` docs trying to suss out what the default formats are for various cases and what options they support.  Learned quite a few things but there's definitely some dark corners still.

In case anyone else finds this with the same questions I had:

## `git stash show <ref>`

This command is [built on top of `git diff` and can take any of its options](https://git-scm.com/docs/git-stash#git-stash-showltstashgt).  By default, it does output a diffstat (NB: this is probably what you meant in your first line instead of `git show <ref>`.)  But it can take `--patch`, which makes it output a diff in patch format, which `cdiff` can parse (as you suggested).

## `git show <object>`

This is a multipurpose command to display several kinds of things.

- When `<object>` is a **non-merge commit**, the default output is in two parts: 1) a header with the commit author/date/message and 2) a diff body generated by a normal `git diff` (you can see this by running, e.g., `diff -us <(git show) <(git diff HEAD~1 HEAD)` as long as the last commit wasn't a merge).  `cdiff` can parse the output for this case just fine.

- When `<object>` is a **merge commit**, [by default `git show` uses `git diff`'s `--cc` option to generate a *combined diff*](https://git-scm.com/docs/git-show#_combined_diff_format).  `cdiff` can't parse the output for this case.

- When `<object>` is a **stash ref**, it's *always* going to be a merge commit, because of the way stashes are stored.

However, if the `-m` option is used (`git show -m <object>`), multiple single diffs are generated instead, and `cdiff` *can* parse those. (Though in the case of stashes, you'll basically be seeing two copies of the same diff)

So both of these work:
```bash
git stash show -p stash@{1} | cdiff -s    # longer, one diff
git show -m stash@{1} | cdiff -s          # shorter, two diffs
```

**Comment by ymattw** [comment]
Thank you for giving those very useful information.  I am closing this issue because it's intended behavior.
