### ISSUE TITLE
If LESS environment variable is defined, cdiff displays raw colour codes

### ISSUE THREAD

**Issue by Jehops** [ymattw/cdiff#67]
`LESS="anything" cdiff` will cause `cdiff` to display raw colour codes instead of colours.  This is with `cdiff-1.0.3` installed via the FreeBSD package.

**Comment by ymattw** [comment]
If you set `LESS`  environment, cdiff considers you want to control the behavior of `less` yourself completely. In your case you are missing the `-R` option for less.

FYI cdiff use this as default options for `less`: `['-FRSX', '--shift 1'`.
