### ISSUE TITLE
Python API?

### ISSUE THREAD

**Issue by jakubka** [ymattw/cdiff#68]
Hi,

Apologies if this was asked already.. couldn't find the answer.

Is it possible to use `cdiff` programmatically from the Python script?

Something like this:

```
import cdiff

diff_string = get_diff_somehow()

cdiff.print_colorized(diff_string)
``` 

This would be super useful for the utility we are writing.

Thanks!

**Comment by ymattw** [comment]
`DiffParser` and `DiffMarker` might be what you want, I imagine you will have the same logic as [1], sorry I don't have enough docstring in the file.

[1] https://github.com/ymattw/cdiff/blob/a1a33a52/cdiff.py#L642-L647

**Comment by jakubka** [comment]
It works well, thanks @ymattw!

Here is the basic usage if anyone's interested:

```python
import sys
from io import StringIO

from cdiff import (
  PatchStream,
  DiffParser,
  DiffMarker,
)

diff_str = """\
diff --git a/file.txt b/file.txt
index ada066f..a252b8c 100644
--- a/file.txt
+++ b/file.txt
@@ -1,4 +1,4 @@
 line 1
-line 2
-line 3
+this is a new line
+line change 3

"""

raw_stream = StringIO(diff_str) # open('file.diff', 'r')

stream = PatchStream(raw_stream)
diffs = DiffParser(stream).get_diff_generator()
marker = DiffMarker()
color_diff = marker.markup(diffs)

for line in color_diff:
    sys.stdout.write(line)
```
