### ISSUE TITLE
Add an option to wrap long lines in side-by-side view

### ISSUE THREAD

**Issue by dimonomid** [ymattw/cdiff#71]
Currently, long lines are just truncated with a trailing `>` char, which is not too useful. Would be better to wrap long lines.

What do you think?

**Comment by dimonomid** [comment]
Fyi I'll implement that feature, already started working on it and it looks like it's not hard to implement. Will send a PR once I have it in place.

**Comment by ymattw** [comment]
Hi Dmitry, if you found a way to display long lines in a good way, that
would be a nice feature to add. Thanks for your interest and contribution!

**Comment by ymattw** [comment]
Was fixed by #72.
