### ISSUE TITLE
cdiff is breaking blocks

### ISSUE THREAD

**Issue by snoblenet** [ymattw/cdiff#75]
Let's say I have...
```
case: 'one';
  return 'yes, one';
  break;
```
...and I change it to...
```
case: 'one';
  return 'yes, one';
  break;
case: 'two';
  return 'yes, two';
  break;
```
...then `git diff` will correctly identify the change as...
```
case: 'two';
  return 'yes, two';
  break;
```
...but if I pipe `git diff` to `cdiff`, it shows the change as:
```
  break;
case: 'two';
  return 'yes, two';
```
How can I fix this? Thanks.

**Comment by snoblenet** [comment]
To clarify, in the above minimal case, `cdiff` does actually work correctly.

But in a slightly more complex case designed to mimic real usage conditions, it fails in the way described above.

The slightly more complex case is...

Before:
```
case: 'one';
  return 'yes, one';
  break;
case: 'two';
  return 'yes, two';
  break;
```
After:
```
case: 'one';
  return 'yes, one';
  break;
case 'one-point-five';
  return 'yes, one-point-five';
  break;
case: 'two';
  return 'yes, two';
  break;
```
In that case `git diff` correctly identifies the added text as:
```
case 'one-point-five';
  return 'yes, one-point-five';
  break;
```
But when piped to `cdiff`, the change is presented as:
```
  break;
case 'one-point-five';
  return 'yes, one-point-five';
```

**Comment by ymattw** [comment]
It's a behavior of python difflib, which is slightly different to git/svn diff and patchutils, I imagine enhancing this requires to touch core diff algorithm in difflib.  I agree it's confusing but IMHO not worth to "fix" as the diff format is still right. Thanks for reporting!
